name: Auto merge

on:
  pull_request

jobs:
  automerge:
    name: Auto merge after successful checks
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          MERGE_LABELS: Update
          MERGE_METHOD: rebase
