name: "Build Deployment"

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - name: Start Obfuscating
        run: |
          rm -rf .github .gitignore .vscode lgu-ms.sql README.md .htaccess .git .replit replit.nix animated-roped-off-construction-barracades.gif dev
          rm -rf obfuscate node_modules package.json package-lock.json .prettierrc.json include/config.php js/grecaptcha.js
      - name: Push to deployment Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'lgu-ms'
          destination-repository-name: 'lgu-ms'
          user-email: mrepol742@gmail.com
          commit-message: Initial Commit
          target-branch: deployment

          
        # npm i
        # cd obfuscate
        #  node obfuscate.js
        #  cd ..