name: "Security Checker"

on:
  push:
    branches: [ "master", "deployment"]
  pull_request:
    branches: [ "master", "deployment"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - name: Security Checker
        run: |
          composer install --prefer-dist --no-progress
          php vendor/bin/security-checker security:check composer.lock